// All data comes from free, key-less public APIs, fetched client-side.
// Every call fails soft: a broken layer never blocks the rest of the app.

import { demoPlaceLookup } from './demo.js'
import { fetchOverpass } from './overpass.js'

const cache = new Map()

async function cachedJson(key, url, options, timeoutMs) {
  if (cache.has(key)) return cache.get(key)
  let res
  if (timeoutMs) {
    const controller = new AbortController()
    const timer = setTimeout(() => controller.abort(), timeoutMs)
    try {
      res = await fetch(url, { ...options, signal: controller.signal })
    } catch (e) {
      throw e.name === 'AbortError' ? new Error(`timed out after ${timeoutMs}ms for ${url}`) : e
    } finally {
      clearTimeout(timer)
    }
  } else {
    res = await fetch(url, options)
  }
  if (!res.ok) throw new Error(`${res.status} for ${url}`)
  const data = await res.json()
  cache.set(key, data)
  return data
}

// ——— Offline demo snapshots ———
// If app/public/demo/<key>.json exists (generated by scripts/capture-demo-data.mjs),
// serve it instantly instead of hitting the network. Missing snapshot → live fetch.
const snapshotMisses = new Set()

async function loadSnapshot(key) {
  if (snapshotMisses.has(key)) return null
  if (cache.has(`snap:${key}`)) return cache.get(`snap:${key}`)
  try {
    const res = await fetch(`${import.meta.env.BASE_URL}demo/${key}.json`)
    if (!res.ok) throw new Error('no snapshot')
    const data = await res.json()
    cache.set(`snap:${key}`, data)
    return data
  } catch {
    snapshotMisses.add(key)
    return null
  }
}

const ICONIC_TAXA = 'Mammalia,Aves,Reptilia,Amphibia,Actinopterygii,Mollusca,Insecta,Arachnida'

/** Recent wild animal observations (with photos) around a point, from iNaturalist. */
export async function fetchWildSightings(lat, lng, radiusKm = 12, perPage = 60) {
  const key = `inat:${lat.toFixed(3)},${lng.toFixed(3)},${radiusKm},${perPage}`
  const url =
    `https://api.inaturalist.org/v1/observations?lat=${lat}&lng=${lng}&radius=${radiusKm}` +
    `&iconic_taxa=${ICONIC_TAXA}&photos=true&quality_grade=research` +
    `&per_page=${perPage}&order_by=observed_on&order=desc`
  const data = await cachedJson(key, url)
  return (data.results || [])
    .map((o) => {
      const [lngc, latc] = o.geojson?.coordinates || []
      const t = o.taxon
      if (latc == null || !t) return null
      return {
        kind: 'wild',
        id: `w${o.id}`,
        lat: latc,
        lng: lngc,
        commonName: t.preferred_common_name || t.name,
        sciName: t.name,
        taxonId: t.id,
        iconicTaxon: t.iconic_taxon_name || 'Unknown',
        photo: o.photos?.[0]?.url || null, // "square" 75px thumbnail
        photoLarge: o.photos?.[0]?.url?.replace('square', 'medium') || null,
        observedOn: o.observed_on || null,
        placeGuess: o.place_guess || null,
        conservation: t.conservation_status?.status || null,
        wikipediaUrl: t.wikipedia_url || null,
        inatUrl: o.uri || `https://www.inaturalist.org/observations/${o.id}`,
      }
    })
    .filter(Boolean)
}

// Overpass fragments shared by nearby + route queries. `around` is the
// spatial filter (a point radius, or a polyline corridor).
export const buildCorePlaceFilters = (around) => `
  nwr["tourism"~"^(zoo|aquarium)$"]${around};
  nwr["zoo"]${around};
  nwr["landuse"="farmyard"]["name"]${around};
  nwr["animal"~"petting|boarding"]${around};
`

/** Zoos, aquariums, farms and wildlife places around a point, from OpenStreetMap. */
export async function fetchAnimalPlaces(lat, lng, radiusM = 12000) {
  return overpassPlaces(buildCorePlaceFilters(`(around:${radiusM},${lat},${lng})`))
}

/** Same as fetchAnimalPlaces but along a route corridor (Overpass linestring `around`). */
export async function fetchPlacesAlongRoute(latlngs, radiusM = 4000) {
  const chain = latlngs.map(([la, ln]) => `${la},${ln}`).join(',')
  return overpassPlaces(buildCorePlaceFilters(`(around:${radiusM},${chain})`))
}

async function overpassPlaces(body) {
  const query = `[out:json][timeout:25];(${body});out center tags 60;`
  const key = `ovp:${query}`
  const data = cache.has(key) ? cache.get(key) : await fetchOverpass(query)
  cache.set(key, data)
  return mapOverpassElements(data)
}

export function mapOverpassElements(data) {
  return (data.elements || [])
    .map((el) => {
      const lat = el.lat ?? el.center?.lat
      const lng = el.lon ?? el.center?.lon
      const tags = el.tags || {}
      const name = tags.name || tags['name:en']
      if (lat == null || !name) return null
      const type =
        tags.tourism === 'aquarium' ? 'aquarium'
        : tags.tourism === 'zoo' || tags.zoo ? 'zoo'
        : tags.leisure === 'bird_hide' ? 'bird_hide'
        : tags.landuse === 'farmyard' ? 'farm'
        : 'cafe'
      return {
        kind: 'place',
        id: `p${el.type}${el.id}`,
        lat, lng, name, type,
        website: tags.website || tags['contact:website'] || null,
        openingHours: tags.opening_hours || null,
      }
    })
    .filter(Boolean)
}

/** Free-text place name → coordinates. Demo places resolve instantly; else Nominatim. */
export async function geocode(q) {
  const demo = demoPlaceLookup(q)
  if (demo) return demo
  const url = `https://nominatim.openstreetmap.org/search?format=json&limit=1&q=${encodeURIComponent(q)}`
  const data = await cachedJson(`geo:${q}`, url)
  if (!data[0]) throw new Error(`Could not find “${q}”`)
  return { lat: +data[0].lat, lng: +data[0].lon, label: data[0].display_name.split(',')[0] }
}

/** Road route between two points via the public OSRM demo server. */
export async function fetchRoute(from, to) {
  const url =
    `https://router.project-osrm.org/route/v1/driving/${from.lng},${from.lat};${to.lng},${to.lat}` +
    `?overview=full&geometries=geojson`
  const data = await cachedJson(`osrm:${url}`, url)
  const r = data.routes?.[0]
  if (!r) throw new Error('No road route found between those places')
  return {
    latlngs: r.geometry.coordinates.map(([ln, la]) => [la, ln]),
    distanceKm: r.distance / 1000,
    durationMin: r.duration / 60,
  }
}

/** Short encyclopedia summary for an animal, via Wikipedia. */
export async function fetchWikiSummary(sighting) {
  const title = sighting.wikipediaUrl
    ? decodeURIComponent(sighting.wikipediaUrl.split('/wiki/')[1] || '')
    : sighting.commonName
  if (!title) return null
  try {
    const data = await cachedJson(
      `wiki:${title}`,
      `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`,
    )
    return { extract: data.extract, url: data.content_urls?.desktop?.page }
  } catch {
    return null
  }
}

/** Pick `count` points spread evenly along a polyline (for corridor sampling). */
export function samplePolyline(latlngs, count = 6) {
  if (latlngs.length <= count) return latlngs
  const step = (latlngs.length - 1) / (count - 1)
  return Array.from({ length: count }, (_, i) => latlngs[Math.round(i * step)])
}

/** Thin a polyline down to at most `max` points (Overpass query size limit). */
export function simplifyPolyline(latlngs, max = 30) {
  if (latlngs.length <= max) return latlngs
  const step = (latlngs.length - 1) / (max - 1)
  return Array.from({ length: max }, (_, i) => latlngs[Math.round(i * step)])
}

export function dedupeByTaxon(sightings) {
  const seen = new Set()
  return sightings.filter((s) => {
    if (seen.has(s.taxonId)) return false
    seen.add(s.taxonId)
    return true
  })
}

// ——— Wild distribution aggregation ———
// Wild animals aren't pinned to an exact spot: we group a species' observations
// into a soft "range" — a centroid plus a spread radius — so the map shows where
// each animal is generally found around the area, not a misleading precise point.
const R_EARTH = 6371000
function metersBetween(a, b) {
  const dLat = ((b.lat - a.lat) * Math.PI) / 180
  const dLng = ((b.lng - a.lng) * Math.PI) / 180
  const lat = ((a.lat + b.lat) / 2) * (Math.PI / 180)
  const x = dLng * Math.cos(lat)
  return Math.sqrt(dLat * dLat + x * x) * R_EARTH
}

export function aggregateSpecies(sightings, { minM = 350, maxM = 2600 } = {}) {
  const groups = new Map()
  for (const s of sightings) {
    if (!groups.has(s.taxonId)) groups.set(s.taxonId, [])
    groups.get(s.taxonId).push(s)
  }
  const out = []
  for (const points of groups.values()) {
    const centroid = {
      lat: points.reduce((a, p) => a + p.lat, 0) / points.length,
      lng: points.reduce((a, p) => a + p.lng, 0) / points.length,
    }
    // Spread = mean distance to centroid, softened and clamped. A lone sighting
    // still gets a gentle minimum halo so it reads as "seen around here."
    const meanDist = points.reduce((a, p) => a + metersBetween(centroid, p), 0) / points.length
    const spreadM = Math.max(minM, Math.min(maxM, meanDist * 1.4 || minM))
    const rep = points.find((p) => p.photo) || points[0]
    const legs = points.map((p) => p.routeLeg).filter((l) => l != null)
    out.push({
      ...rep,
      lat: centroid.lat,
      lng: centroid.lng,
      count: points.length,
      spreadM,
      routeLeg: legs.length ? Math.min(...legs) : undefined,
    })
  }
  // Most-observed species first — steadier presence drawn on top.
  return out.sort((a, b) => b.count - a.count)
}

// ——— High-level scenario loaders (snapshot-first) ———
// Demo scenarios pass a `snapshotKey`; if a captured JSON exists it loads instantly
// and offline. Any other search passes no key and always fetches live.

export async function getNearbyData(lat, lng, snapshotKey) {
  if (snapshotKey) {
    const snap = await loadSnapshot(snapshotKey)
    if (snap) return { wild: snap.wild || [], places: snap.places || [], fromSnapshot: true }
  }
  const [wild, places] = await Promise.all([
    fetchWildSightings(lat, lng).catch(() => []),
    fetchAnimalPlaces(lat, lng).catch(() => []),
  ])
  return { wild, places, fromSnapshot: false }
}

export async function getRouteData(from, to, snapshotKey) {
  if (snapshotKey) {
    const snap = await loadSnapshot(snapshotKey)
    if (snap?.route) {
      return { route: snap.route, wild: snap.wild || [], places: snap.places || [], fromSnapshot: true }
    }
  }
  const route = await fetchRoute(from, to)
  const samples = samplePolyline(route.latlngs, 6)
  const [batches, places] = await Promise.all([
    Promise.all(samples.map(([la, ln]) => fetchWildSightings(la, ln, 6, 30).catch(() => []))),
    fetchPlacesAlongRoute(simplifyPolyline(route.latlngs)).catch(() => []),
  ])
  // Order encounters by which leg of the route first found them.
  const seen = new Set()
  const wild = []
  batches.forEach((batch, leg) => {
    for (const s of batch) {
      if (seen.has(s.id)) continue
      seen.add(s.id)
      wild.push({ ...s, routeLeg: leg })
    }
  })
  return { route, wild, places, fromSnapshot: false }
}
